---
  - name: add rabbitmq official apt repository
    apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

  - name: add trusted key
    apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present

  - name: install package
    apt: name={{ item }} update_cache=yes state=installed
    with_items:
      - rabbitmq-server

  - name: enable rabbitmq plugins
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
    notify:
    - restart rabbitmq

  - name: add users
    rabbitmq_user: user={{ rabbitmq.user }} password={{ rabbitmq.password }} tags=administrator,{{ rabbitmq.user }} vhost=/ configure_priv=.* write_priv=.* read_priv=.* state=present

  - name: remove default guest user
    rabbitmq_user: user=guest state=absent

  - name: ensure vhost /test is present
    rabbitmq_vhost: name=/test state=present