---
- name: ensure timezone is set
  lineinfile: dest=/etc/php{{ php.version }}/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  lineinfile: dest=/etc/php{{ php.version }}/fpm/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'
